"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { clearMistakes, readProgress, removeMistake } from "@/lib/progress";
import type { Quiz, QuizMistake, QuizQuestion } from "@/lib/types";
import { QuizPanel } from "./QuizPanel";
function todayKey(){const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
function pickToday(m:QuizMistake[],limit=10){if(m.length<=limit)return m;const sorted=[...m].sort((a,b)=>a.at.localeCompare(b.at)),oldest=sorted.slice(0,4);let h=2166136261;for(const c of todayKey()){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}const shuffled=sorted.filter(x=>!oldest.some(o=>o.id===x.id));for(let i=shuffled.length-1;i>0;i--){h=(Math.imul(h,1664525)+1013904223)>>>0;const j=h%(i+1);[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}return [...oldest,...shuffled].slice(0,limit)}
export function ReviewClient(){
 const [questionBank,setQuestionBank]=useState<Record<string,QuizQuestion>>({});
 const [mistakes,setMistakes]=useState<QuizMistake[]>([]),[session,setSession]=useState<QuizMistake[]|null>(null),[sessionNumber,setSessionNumber]=useState(0);
 const sync=useCallback(()=>{const current=(readProgress().mistakes??[]).map(m=>{const q=questionBank[m.id];if(!q)return m;const chosen=q.choices.find(c=>c.text===m.chosenText)?.id??"";return{...m,prompt:q.prompt,choices:q.choices,answer:q.answer,explanation:q.explanation,chosen,chosenText:chosen?m.chosenText:`${m.chosenText} (개정 전 선택지)`,answerText:q.choices.find(c=>c.id===q.answer)?.text??q.answer}});setMistakes(current);setSession(prev=>prev===null?pickToday(current):prev.map(item=>current.find(next=>next.id===item.id)??item))},[questionBank]);
 useEffect(()=>{sync();window.addEventListener("history-ebook:progress",sync);window.addEventListener("storage",sync);return()=>{window.removeEventListener("history-ebook:progress",sync);window.removeEventListener("storage",sync)}},[sync]);
 useEffect(()=>{const ids=(readProgress().mistakes??[]).map(m=>m.id);if(!ids.length)return;const controller=new AbortController();fetch("/api/review-questions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ids}),signal:controller.signal}).then(r=>r.ok?r.json():{}).then(setQuestionBank).catch(()=>{});return()=>controller.abort()},[]);
 const today=useMemo(()=>session??[],[session]);const quiz:Quiz|null=useMemo(()=>today.length?{lessonId:"review",version:2,questions:today.map(m=>({id:m.id,prompt:m.prompt,choices:m.choices,answer:m.answer,explanation:m.explanation,sourceLessonKey:m.lessonKey,sourceQuestionId:m.questionId,sourceHref:m.href}))}:null,[today]);
 if(!mistakes.length&&!today.length)return <div className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-slate-600 dark:border-slate-700 dark:text-slate-400"><p>저장된 오답이 없습니다. 차시 퀴즈를 풀면 틀린 문항이 여기에 모입니다.</p><p className="mt-4"><Link href="/korean" className="underline">한국사 학습 시작</Link></p></div>;
 return <div className="space-y-8"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600 dark:text-slate-400">저장된 오답 {mistakes.length}문항 · 이번 복습 {today.length}문항</p><button type="button" onClick={()=>{if(confirm("오답 노트를 모두 지울까요?")){clearMistakes();setSession([]);sync()}}} className="min-h-11 rounded-lg border px-4 text-sm">오답 모두 삭제</button></div><button type="button" onClick={()=>{setSession(pickToday(mistakes));setSessionNumber(n=>n+1)}} className="min-h-11 rounded-lg border px-4 text-sm">남은 오답으로 새 복습 시작</button>{quiz&&<QuizPanel key={sessionNumber} quiz={quiz} lessonKey="review/mistakes" href="/review" title="오늘 복습"/>}<details><summary className="cursor-pointer py-3 font-medium">오답 목록과 정답 보기 ({mistakes.length}문항)</summary><ul className="space-y-3">{mistakes.map(m=><li key={m.id} className="rounded-xl border p-4"><p className="font-medium">{m.prompt}</p><p className="mt-2 text-sm text-rose-700">내 답: {m.chosenText}</p><p className="text-sm text-emerald-700">정답: {m.answerText}</p>{m.explanation&&<p className="mt-1 text-sm text-slate-600">{m.explanation}</p>}<div className="mt-3 flex gap-3 text-sm"><Link href={m.href} className="underline">해당 차시</Link><button onClick={()=>{removeMistake(m.id);sync()}}>목록에서 빼기</button></div></li>)}</ul></details></div>
}
